[main]
name    = "Wiish Mac Demo"
version = "0.1.0"
src     = "basicmac.nim"
dst     = "./dist"
include = []

[macos]
bundle_identifier = "com.example.wiish.basicmac"
category_type = "public.app-category.example"
