[main]
version = "0.1.0"
name    = "Wiish Font Demo"
distDir = "./dist"
bin     = "./fonts"
include = [
  "Lato-Regular.ttf",
]

[macos]
bundle_identifier = "com.example.myapp"
category_type = "public.app-category.example"