

language: c

cache: ccache
cache:
  directories:
  - .cache

matrix:
  include:
    - os: linux
      env: CHANNEL=stable
      compiler: gcc

    - os: linux
      env: CHANNEL=devel
      compiler: gcc

    # Android testing
    # - os: linux
    #   env:
    #   - CHANNEL=stable
    #   - WIISH_BUILD_ANDROID=yes
    #   compiler: gcc
    #   language: android
    #   android:
    #     components:
    #       - build-tools-26.0.2
    #       - android-26
    #       - sys-img-x86-android-26
    #       - sys-img-armeabi-v7a-android-17
    #     # licenses:
    #     #   - 'android-sdk-preview-license-52d11cd2'
    #     #   - 'android-sdk-license-.+'
    #     #   - 'google-gdk-license-.+'

    - os: osx
      env: CHANNEL=stable
      compiler: clang

  allow_failures:
    - env: CHANNEL=devel
  fast_finish: true

addons:
  apt:
    packages:
      - xorg-dev

install:
  # - if [[ "$WIISH_BUILD_ANDROID" == "yes" ]]; then yes | sdkmanager ndk-bundle; fi
  # - if [[ "$WIISH_BUILD_ANDROID" == "yes" ]]; then sdkmanager --update && yes | sdkmanager --licenses; fi
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim $CHANNEL

script:
  - nimble refresh
  - nimble test
  - tests/dochecks.sh
  - ./builddocs.sh

branches:
  except:
    - gh-pages

