[desktop]
name     = "Wiish Demo"
version  = "0.1.0"
src      = "main_desktop.nim"
dst      = "dist"
nimflags = []

[mobile]
name     = "Wiish"
version  = "0.1.0"
src      = "main_mobile.nim"
dst      = "dist"
nimflags = []

[macos]
bundle_identifier = "com.wiish.exampledesktop"
category_type = "public.app-category.example"

[ios]
bundle_identifier = "com.wiish.examplemobile"
