[main]
version      = "0.1.0"
dst          = "dist"
windowFormat = "webview"

[desktop]
name        = "Webview Demo"
src         = "main_desktop.nim"
# Path to an image file to use for the application icon.
# The file will automatically be converted to the correct
# format.
icon        = ""

[mobile]
name        = "Webview"
src         = "main_mobile.nim"
icon        = ""

[macos]
bundle_identifier = "com.wiish.webview"
category_type = "public.app-category.example"

[ios]
bundle_identifier = "com.wiish.webview"
sdk_version = "" # If blank, auto-detect the latest installed version