[desktop]
name     = "Wiish Basic Demo"
version  = "0.1.0"
src      = "desktop.nim"
dst      = "./dist"
nimflags = []

[macos]
bundle_identifier = "com.example.wiish.basic"
category_type = "public.app-category.example"
