[main]
version      = "0.1.0"
dst          = "./dist"
windowFormat = "sdl"

[desktop]
name     = "Wiish OpenGL Demo"
src      = "main_desktop.nim"

[mobile]
name     = "WiishOpenGL"
src      = "main_mobile.nim"

[macos]
bundle_identifier = "com.example.wiish.opengl"
category_type = "public.app-category.example"

[ios]
bundle_identifier = "com.example.wiish.opengl"
sdk_version = ""
